## YAML Template.

main: me.prokopyl.commandtools.CommandTools
name: CommandTools
version: 0.0.0a
author: ProkopyL

commands:
   ctool:
      description: This is a demo command.
      usage: /<command> [player]
      permission: commandtools.ctools
      permission-message: You don't have <permission>
      
## TODO - Finir la gestion de l'outil avec NBT
##      - Gérer la sauvegarde des outils
##      - Gérer de multiples outils en même temps pour chaque joueur (ToolStore)