## YAML Template.

main: me.prokopyl.commandtools.CommandTools
name: CommandTools
version: 1.0
author: ProkopyL

commands:
   ctool:
      description: Manages and creates Command Tools.
      usage: /<command> [new|get|list|edit|rename|delete]
      permission: commandtools.ctools
      permission-message: §cYou are not allowed to use Command Tools.
      