## YAML Template.

main: me.prokopyl.commandtools.CommandTools
name: CommandTools
version: 0.0.9a
author: ProkopyL

commands:
   ctool:
      description: Manages and creates Command Tools.
      usage: /<command> [new|edit|rename]
      permission: commandtools.ctools
      permission-message: You don't have <permission>
      