## YAML Template.

main: me.prokopyl.commandtools.CommandTools
name: CommandTools
version: 1_beta
author: ProkopyL

commands:
   ctool:
      description: Manages and creates Command Tools.
      usage: /<command> [new|get|list|edit|rename|delete]
      permission: commandtools.ctools
      permission-message: You don't have <permission>
      